version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/CollectDaprStats"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"