### NuGet
@nugetPackage=Dapr.Client
GET https://azuresearch-usnc.nuget.org/query?q=PackageId:{{nugetPackage}}

### NPM
## https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md
## use url encoded form of @dapr/dapr
@npmPackage=@dapr%2Fdapr

GET https://registry.npmjs.org/{{npmPackage}}

### NPM downloads
## https://github.com/npm/registry/blob/master/docs/download-counts.md

@period=last-week

GET https://api.npmjs.org/downloads/point/{{period}}/{{npmPackage}}

### Get version downloads
GET https://api.npmjs.org/versions/{{npmPackage}}/{{period}}



### ---
## PyPi Stats
GET https://pypistats.org/api/packages/dapr/recent

### ---
## PyPi Stats Dapr-Agents
GET https://pypistats.org/api/packages/dapr-agents/recent


### ---
### Discord
@apiVersion=10
GET https://discord.com/api/v{{apiVersion}}/guilds/{{discordServerId}}?with_counts=true
User-Agent: DiscordBot (https://discord.com/api/, {{apiVersion}})
Authorization: Bot {{discordToken}}

@namespace=daprio
@repository=daprd
@tag=1.16.5
### ---
### Docker Hub 
GET https://registry.hub.docker.com/v2/repositories/{{namespace}}/{{repository}}/tags/{{tag}}
 
### Docker Hub (for bi-weekly community metrics)
GET https://hub.docker.com/v2/namespaces/{{namespace}}/repositories/{{repository}}


 @ghToken=
### GitHub Dapr image
GET https://api.github.com/orgs/dapr/packages/container/dapr
Authorization: Bearer {{ghToken}} 