{
 "title": "Dapr stats 2025",
 "description": "Dapr community and SDK metrics. This data gets updated twice a month.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SDKs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": ".NET SDK downloads (all versions, weekly average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "daprstats",
     "rawSql": "SELECT collection_date, package_version, download_count_increment FROM nuget_dapr_client_view WHERE collection_date >= '2025-01-01' ORDER BY collection_date ASC LIMIT 1000 "
    }
   ]
  },
  {
   "title": "Python SDK downloads (all versions, weekly average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "daprstats",
     "rawSql": "SELECT download_count, collection_date FROM python_dapr WHERE collection_date >= '2025-01-01 00:00:00.000' ORDER BY collection_date ASC LIMIT 1000 "
    }
   ]
  },
  {
   "title": "JavaScript SDK downloads (all versions, weekly average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "daprstats",
     "rawSql": "SELECT collection_date, download_count FROM npm_dapr_dapr WHERE collection_date >= '2025-01-01 00:00:00.000' ORDER BY collection_date ASC LIMIT 1000 "
    }
   ]
  },
  {
   "title": "Java SDK downloads (all versions, weekly average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "daprstats",
     "rawSql": "SELECT collection_date, avg_weekly_downloads FROM java_dapr_sdk_view WHERE collection_date >= '2025-01-01' ORDER BY collection_date ASC LIMIT 1000 "
    }
   ]
  },
  {
   "title": "Community",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dapr Discord Users (cumulative)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "daprstats",
       "rawSql": "SELECT collection_date, member_count FROM discord_dapr WHERE collection_date >= '2025-01-01 00:00:00.000' ORDER BY collection_date LIMIT 500 "
      }
     ]
    },
    {
     "title": "GitHub Forks and Stars (dapr/dapr)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "daprstats",
       "rawSql": "SELECT repo_name, collection_date, fork_count_total, star_count_total FROM github_dapr WHERE collection_date >= '2025-01-01 00:00:00.000' ORDER BY collection_date ASC LIMIT 1000 "
      }
     ]
    },
    {
     "title": "Dapr Website & Docs Users (cumulative for 2025)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "daprstats",
       "rawSql": "SELECT collection_date, user_count FROM website_dapr WHERE collection_date >= '2025-01-01 00:00:00.000' ORDER BY collection_date ASC LIMIT 1000 "
      }
     ]
    },
    {
     "title": "GitHub stats for all dapr repos (weekly average)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "daprstats",
       "rawSql": "SELECT repo_name, collection_date, avg_weekly_issue_count, avg_weekly_comment_count, avg_weekly_commit_count, avg_weekly_pullrequest_count, avg_weekly_distinct_user_count FROM weekly_github_counts_dapr WHERE collection_date >= '2025-01-01 00:00:00.000' ORDER BY collection_date LIMIT 1000 "
      }
     ]
    },
    {
     "title": "Dapr YouTube Views (cumulative for 2025)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "daprstats",
       "rawSql": "SELECT collection_date, view_count FROM youtube_dapr WHERE collection_date >= '2025-01-01 00:00:00.000' ORDER BY collection_date ASC LIMIT 1000 "
      }
     ]
    }
   ]
  }
 ]
}