--- Insert Dapr website records manually
-- Collect cumulative users from Jan 1, 2024.
-- From Jan 1, 2024 to [Month] 1, 2024 (or [Month] 16, 2024) 
INSERT INTO website_dapr (collection_date, user_count)
VALUES ('2024-04-01 00:00:00', 1828);


--- Insert Dapr YouTube records manually
-- Collect cumulative users from Jan 1, 2024.
-- From Jan 1, 2024 to [Month] 1, 2024 (or [Month] 16, 2024) 
INSERT INTO youtube_dapr (collection_date, view_count)
VALUES ('2024-04-01 00:00:00', 30000);


