name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '9.0.x'

        - name: Restore dependencies
          run: dotnet restore ./CollectDaprStats/CollectDaprStats.csproj

        - name: Build solution
          run: dotnet build ./CollectDaprStats/CollectDaprStats.csproj --configuration Release
